import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import "../components/Infrastructure/InfrastructureSection.css";

import Intro from "@/components/Intro";
import CustomScrollBar from "@/components/CustomScrollBar";
import SmoothScroll from "@/components/SmoothScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        {/* Fixed intro MUST stay outside ScrollSmoother */}
        <Intro />

        {/* Main page gets smooth scrolling */}
        <SmoothScroll>
          {children}
        </SmoothScroll>

        {/* Fixed scrollbar also stays outside */}
        <CustomScrollBar />
      </body>
    </html>
  );
}